DROP SCHEMA IF EXISTS senla;
CREATE SCHEMA senla;
USE senla;
CREATE TABLE place (
id UUID NOT NULL PRIMARY KEY,
calendar ARRAY NOT NULL);
CREATE TABLE master(
id UUID NOT NULL PRIMARY KEY,
calendar ARRAY NOT NULL,
fullname VARCHAR(255) NOT NULL,
dailypayment DOUBLE NOT NULL,
speciality ENUM('MECHANIC','RESHAPER','ELECTRICIAN',
'PAINTER') NOT NULL);
CREATE TABLE order
