CREATE DATABASE IF NOT EXISTS senla;

USE senla;

CREATE TABLE product (
maker VARCHAR(10) NOT NULL, 
model VARCHAR(50) NOT NULL PRIMARY KEY, 
type VARCHAR(50) NOT NULL),
;

CREATE TABLE pc (
code INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
model VARCHAR(50) NOT NULL NULL,
speed SMALLINT NOT NULL,
ram SMALLINT NOT NULL,
hd REAL NOT NULL,
cd VARCHAR(10) NOT NULL,
price DECIMAL(10,4),
UNIQUE (model),
FOREIGN KEY (model) REFERENCES product (model) ON DELETE CASCADE);

CREATE TABLE laptop(
code INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
model VARCHAR(50) NOT NULL NULL,
speed SMALLINT NOT NULL,
ram SMALLINT NOT NULL,
hd REAL NOT NULL,
screen TINYINT NOT NULL,
price DECIMAL(10,4),
UNIQUE (model),
FOREIGN KEY (model) REFERENCES product (model) ON DELETE CASCADE);

CREATE TABLE printer(
code INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
model VARCHAR(50) NOT NULL NULL,
color CHAR(1) NOT NULL,
type VARCHAR(10) NOT NULL,
price DECIMAL(10,4),
UNIQUE (model),
FOREIGN KEY (model) REFERENCES product (model) ON DELETE CASCADE);
